version: '3.8'
services:
  # This service runs the necessary setup commands once and then exits.
  # The webserver and scheduler will not start until this service is complete.
  airflow-init:
    image: apache/airflow:2.5.1
    entrypoint: ["/usr/bin/dumb-init", "--", "bash", "-c"]
    command: >
      airflow db migrate &&
      airflow db upgrade &&
      airflow users create
        --username airflow
        --firstname Airflow
        --lastname User
        --role Admin
        --email airflow@example.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./features.json:/opt/airflow/features.json
    environment:
      - AIRFLOW_CONN_DB=postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW_HOME=/opt/airflow
    depends_on:
      - postgres

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.5.1
    entrypoint: ["/usr/bin/dumb-init", "--", "airflow", "webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./features.json:/opt/airflow/features.json
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_CONN_DB=postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW_HOME=/opt/airflow
    depends_on:
      - airflow-init

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.5.1
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./features.json:/opt/airflow/features.json
    environment:
      - AIRFLOW_CONN_DB=postgresql://airflow:airflow@postgres/airflow
    depends_on:
      - airflow-init

  # PostgreSQL Database for Airflow
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
